[package]
name = "rasher"
version = "0.1.0"
authors = ["Morten Lohne"]

[dependencies]
time = "0.1.*"
itertools = "0.7.*"
rand = "0.3"
ordered-float = "0.5.*"
rayon = "0.8.*"
log = "0.3.*"
# log4rs = "0.7.*"
lazy_static = "0.2.*"

[dependencies.log4rs]
version = "0.7.*"
default-features = false # do not include the default features
features = ["file_appender"]

[dev-dependencies]
quickcheck = "0.4"

[profile.release]
debug = true