[package]
name = "rasher"
version = "0.1.0"
authors = ["Morten Lohne"]

[dependencies]
lazy_static = "0.2.*"
time = "0.1.*"
itertools = "0.5.*"
rand = "0.3"
ordered-float = "0.4.0"
futures = "0.1"
futures-cpupool = "0.1"
rayon = "0.6.0"