[package]
name = "rasher"
version = "0.1.0"
authors = ["Morten Lohne"]

[dependencies]
time = "0.1.*"
itertools = "0.6.*"
rand = "0.3"
ordered-float = "0.4.*"
rayon = "0.8.*"
log = "0.3.*"
log4rs = "0.7.*"
lazy_static = "0.2.8"

[profile.release]
debug = true