[package]
name = "rasher"
version = "0.1.0"
authors = ["Morten Lohne"]
license = "MIT"

[dependencies]
time = "0.1.*"
itertools = "0.6.*"
rand = "0.3"
ordered-float = "0.4.*"
rayon = "0.8.*"
log = "0.3.*"
log4rs = "0.7.*"


[profile.release]
debug = true